site_name: Centre for Innovation and Entrpreneurship
site_url: https://cie.uoc.ac.in

theme:
  name: 'material'
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: images/logo.png
  favicon: 'images/logo.png'
  features:
    - navigation.footer
    - content.code.copy
    - header.autohide
    - announce.dismiss

  icon:
    annotation: material/arrow-right-circle 
 

#theme: 'readthedocs'
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - smarty
    - attr_list
    - wikilinks
    - codehilite:
        linenums: False
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
       preserve_tabs: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: True
    - pymdownx.tilde

extra_css: ["assets/main.css","assets/lightbox/css/lightbox.min.css"]
extra_javascript: ["assets/lightbox/js/lightbox-plus-jquery.min.js"]

extra:
  palette:
      primary: '#087da1'
      accent: '#00a889'
  generator: false


plugins:
   - search


repo_name: 'cieuoc/cie'
repo_url: 'https://github.com/cieuoc/cie'
copyright: 'Copyright © 2024 <a href="https://cie.uoc.ac.in">CIE-UoC</a>'

nav:
  - Home: 'index.md'
  - Events: 'projects.md'
  - Program Details: 'details.md'
  - Syllabus: 'syllabus.md'

